In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('./Salary_Data.csv')

In [4]:
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [5]:
df.tail()

    YearsExperience  Salary
28             10.3  122391
29             10.5  121872
30             11.0  140000
31             12.0  155000
32             13.0  156000

In [6]:
df['bonus'] = df['Salary'] * 0.10

In [7]:
df.head()

   YearsExperience  Salary   bonus
0              1.1   39343  3934.3
1              1.3   46205  4620.5
2              1.5   37731  3773.1
3              2.0   43525  4352.5
4              2.2   39891  3989.1

In [9]:
df.to_csv('Salary_Data_modified.csv')

In [10]:
df.drop(['Salary'], axis=1)

    YearsExperience    bonus
0               1.1   3934.3
1               1.3   4620.5
2               1.5   3773.1
3               2.0   4352.5
4               2.2   3989.1
5               2.9   5664.2
6               3.0   6015.0
7               3.2   5444.5
8               3.2   6444.5
9               3.7   5718.9
10              3.9   6321.8
11              4.0   5579.4
12              4.0   5695.7
13              4.1   5708.1
14              4.5   6111.1
15              4.9   6793.8
16              5.1   6602.9
17              5.3   8308.8
18              5.9   8136.3
19              6.0   9394.0
20              6.8   9173.8
21              7.1   9827.3
22              7.9  10130.2
23              8.2  11381.2
24              8.7  10943.1
25              9.0  10558.2
26              9.5  11696.9
27              9.6  11263.5
28             10.3  12239.1
29             10.5  12187.2
30             11.0  14000.0
31             12.0  15500.0
32             13.0  15600.0